### ISSUE TITLE
Is Kikaha JAX-RS compliant?

### ISSUE THREAD

**Issue by sixman9** [Skullabs/kikaha#126]
It would be great to be able to generate at least WADL or better still Swagger 2.0, to automate client code stub generation.

Thanks

**Comment by miere** [comment]
Hi @sixman9 

Thanks for asking. Kikaha has an API which design looks quite similar to JAX-RS. It is called uRouting API (micro Routing). This choice was made because the JAX-RS license (CDDL 1.1 or GPL2) isn't quite friendly for enterprise development (we already faced some issues regarding this).

Code stub generation is awesome, we were planning to put it on the road for 1.7.0 version. We have created the issue #29 late on 2014 (shame on us... heheh). At that time, Swagger seems to be the right choice for client generation but there is a lot of Code Generator today (although Swagger still the most popular choice).

Have you ever used another Code Generator. Is Swagger the best today (or good enough)?

**Comment by sizebay** [comment]
Hi @miere 

There is a [nice discussion about this topic at Hacker News](https://news.ycombinator.com/item?id=8912897) that can bring you enlights you to choose which API should be the first one Kikaha will be compatible (if choose one, it doesn't mean that you can make it compatible with another one).

Although, our team have used Swagger for a few months and all we can say is it has been an awesome experience. There is a lot of useful tools that is Swagger compatible and it made our life easier.

Regards

**Comment by miere** [comment]
I'm closing this issue, once it is a duplicated issue from #29.
@sixman9, please, keep track of this topic at #29 from now on.
