### ISSUE TITLE
Any way to debug a kikaha-based project?

### ISSUE THREAD

**Issue by plinyar** [Skullabs/kikaha#173]
I like the ideas behind your library and made it a try. In IntelliJ IDEA I opened kikaha-kotlin project, made some corrections to let it fly, and "mvn kikaha:run" succeeds (sorry, kikaha CLI is too error-prone on Windows).

However, I wanted to debug the project in IntelliJ. To do that, I created debug configuration of type "Maven" and specified "kikaha:run" as parameter. It successfully starts, but any breakpoints set in either UserResource.kt or in generated files are ignored - IntelliJ just doesn't suspend there. If to look at the run console I may see that parameters like "suspend" are passed to JVM. May it be a problem that inner JVM with undertow is not given the debug parameters?

So my question: what is the correct way of debugging kikaha-based apps in IDE like Eclipse of IntelliJ?

And allow me another question just here:
How to run the app without maven? Can I have a plain java class with static void main(...) to run the kikaha and undertow myself?
Sorry, cannot find that in docs.

**Comment by miere** [comment]
Hi @plinyar thank you for your questions. I'm glad you ask, and really glad for your Windows Feedback. I hadn't much time to fix the CLI and made it run as smooth as it run on Linux, but I would be happy to fix it. Would you mind to open a ticket about it to me?

Well, about debugging Kikaha app... The first approach I would suggest is to attach a remote app to your IDE. IntelliJ allows you to attach to a remote app and debugging it easily. To do so, you would add a remote debug configuration (Edit configuration -> Remote). The steps described by [Cory](http://stackoverflow.com/a/30793101/548685) at the SO would guide you on the details. To make your maven app attachable, configure the ```kikaha-maven-plugin``` with the following lines:

```xml
<plugin>
  <groupId>io.skullabs.kikaha</groupId>
  <artifactId>kikaha-maven-plugin</artifactId>
  <configuration>
    <jvmArgs>-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005</jvmArgs>
  </configuration>
</plugin>
```
You may be interested in set ```suspend=y``` in order to your application wait for being attached to the IDE to start the application.

The good old **'public static void main'** approach is a good way to test the app and also a good way to understand how Kikaha works under the hood. Basically, Kikaha can be started by using the ```kikaha.core.cdi.ApplicationRunner``` as _main class_. Or, you can create a main class that calls the ```kikaha.core.cdi.ApplicationRunner.main``` method.

```java
public class KikahaRunner {
  public static void main( String[] args ){
    kikaha.core.cdi.ApplicationRunner.main( args );
  }
}
```

I would also suggest you to another approach, if you don't mind. (Btw, this is my preferred approach)
The most simple way to ensure your Kikaha code is okay is through unit testing. You can test any Kikaha code using the KikahaRunner as JUnitRunner.
```java
import javax.inject.*;
import kikaha.core.test.KikahaRunner;
import kikaha.urouting.api.*;
import org.junit.*;
import org.junit.runner.RunWith;

public class MyService {
  @GET
  public String sayHello(){
    return "Hello";
  }
}

@RunWith( KikahaRunner.class )
public class MyServiceTest {
  
  @Inject MyService myService;

  @Test
  public void shouldBeAbleToSayHello() {
    Assert.assertEquals( "Hello", myService.sayHello() );
  }
}
```
This way you can test any class you made with Kikaha, even those that have Database access.

I hope I've answered your questions. If you have any other doubt, feel free to submit a Question Issue here.

Cheers!

**Comment by miere** [comment]
I just forgot to explain that the ApplicationRunner will end up to execute the [KikahaUndertowServer](https://github.com/Skullabs/kikaha/blob/master/kikaha-core/source/kikaha/core/KikahaUndertowServer.java) class if you have the ```kikaha-core``` on your classpath. At this class you can investigate how Undertow is started on Kikaha.

**Comment by plinyar** [comment]
Thanks a lot. I have created several other tickets as you asked.
