### ISSUE TITLE
Making the new configuration layer introduced on Kikaha 2.0 compatible with the Typesafe Config

### ISSUE THREAD

**Issue by Ibratan** [Skullabs/kikaha#198]
We have a project using Kikaha 1.5.2 which uses the Typesafe configuration library. Once we are trying to migrate to the most recent Kikaha's version, it would be nice if it would be possible to make the former configuration layer with the new one.

**Comment by miere** [comment]
I've patched the current 2.1.0 version (which stills in alpha, but stable) with an 'configuration enrichment' mechanism. This would let you to create an ```Config``` wrapper that would allow you to intercept the all methods on the default Config instance. In practice, you can ask the Typesafe configuration - if it have the data you need you return it, otherwise, you can call the default configuration.

I should close an **alpha7** version later tonight. Let me know if this solve your situation...

**Comment by Ibratan** [comment]
Roger that!! I'll wait for the alpha7 to give it a try and close this issue.

**Comment by Ibratan** [comment]
It seems nice. Thanks!
