### ISSUE TITLE
Security library suggestion

### ISSUE THREAD

**Issue by jmilagroso** [Skullabs/kikaha#215]
Use of [Pac4J](https://github.com/pac4j/undertow-pac4j)

**Comment by miere** [comment]
Hi @jmilagroso 
Thanks for your suggestion, indeed Pac4J was on my radar since @pac4j guys have send an email on the Undertow discussion list but I should confess I didn't include it on roadmap before due to a lack of feedback of this library. Did you have a good experience with @pac4j?

**Comment by jmilagroso** [comment]
Hi @miere.
No,not really. But I think the @pac4j [demo for undertow](https://github.com/jmilagroso/kikaha.rocker/blob/FeaturePac4J/source/pac4j/Server.java) is pretty awesome and should be extensible for the kikaha.

**Comment by jmilagroso** [comment]
May I ask what's on your list for the Security library?

**Comment by miere** [comment]
Hi @jmilagroso 
Yes, indeed, isn't that hard make kikaha compatible with Pac4J. I'll personally take a deep look into that this week. ;)

> May I ask what's on your list for the Security library?

Yes, of course! Although Kikaha is designed to be a micro-service engine, we have included a lot of hooks in order to make its security Life Cycle pretty customizable. Its current version it have only the Undertow's Basic and Form AuthenticationMechanisms and JSON (2.1.x) AuthenticationMechanism. Also, it was pretty integrated with Auth0  (also on 2.1.x) - as requested earlier this year.

I'm expecting to release the 2.1.x beta on June 1. This means that until there it is able to include more features like JWT (which is already planned for this new version), and even Pac4J.

> No,not really. But I think the @pac4j demo for undertow is pretty awesome and should be extensible for the kikaha.

I'm curious, what security framework are you actually using nowadays? Spring Security? JOSSO?
