### ISSUE TITLE
Support for Google Protocol Buffer, Apache Avro

### ISSUE THREAD

**Issue by jmilagroso** [Skullabs/kikaha#238]
Support for Google Protocol Buffer, Apache Avro

**Comment by miere** [comment]
Hi Jay, how is it going?

The 2.1 version is shipped with out-of-box support to protobuf (Google Protocol Buffer).
Take a look at this sample code in order to understand how it works.
https://github.com/Skullabs/kikaha-samples/tree/master/http2-protobuf

Basically this example will cover you how to:
- Configure Kikaha to work with HTTP2
- Use Protobuf to receive and send response on your RPC/REST API

Let me know if this helps you!
Happy 2018 coding!
